version: "3.8"
services:
  web:
    build: ./client
    ports:
      - 3000:3000
  server:
    build: ./server
    ports:
      - 9000:9000
#     environment:
#       DB_URL: mongodb://db/shop
#   db:
#     image: mongo:4.0-xenial
#     ports:
#       - 27017:27017
#     volumes:
#       - dockerComposeTest:/data/db
# volumes:
#   dockerComposeTest:
